language: java

jdk:
  - openjdk11
install:
  - true

script:
  - ./gradlew build -x uploadArchives -x signArchives

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/